#!/bin/bash
# Report Footer — closing banner, metadata, gaps analysis

report_footer() {
    # Report completion banner
    cat << 'EOF'

```
╔══════════════════════════════════════════════════════════════╗
║                  REPORT GENERATION COMPLETE                  ║
╚══════════════════════════════════════════════════════════════╝
```

EOF

    echo "---"
    echo ""
    echo "**$(lang_get 'report_metadata'):**"
    echo "- Generated: \`$(date '+%Y-%m-%d_%H-%M-%S')\`"
    echo "- Cluster: \`$CLUSTER_NAME\`"
    echo "- Kubernetes Version: \`$K8S_VERSION\`"
    echo "- Target Namespaces: \`$TARGET_NAMESPACES\`"
    echo "- Report Type: \`comprehensive_metrics\`"
    echo "- Language: \`$CURRENT_LANG\`"
    echo ""
    echo "---"
    echo ""
    echo "*This report was generated by the Lerian Infrastructure Scoring Tool v${SCRIPT_VERSION}.*"
    echo ""
}
